### ISSUE TITLE
`wget` in GPT4_Retrieval_Augmentation.ipynb example does not download recursively

### ISSUE THREAD

**Issue by neilobremski** [openai/openai-cookbook#319] opened 2023-04-06 12:36 UTC
The following command in `examples/vector_databases/pinecone/GPT4_Retrieval_Augmentation.ipynb` is supposed to recursively download all HTML files recursively for sample data:

```
!wget -r -A.html -P rtdocs https://langchain.readthedocs.io/en/latest/
```

However, it is only downloading the one `index.html`. I tried removing the `-A.html` and even adding `--level 10` but no luck. This happens both in the notebook and both locally when I try to run it on my machine.

**Comment by ted-at-openai** [comment] 2023-04-06 17:57
FYI @jamescalam

**Comment by jamescalam** [comment] 2023-04-10 11:01
@neilobremski @ted-at-openai I submitted a PR to fix this above. The LangChain docs have moved, so running the old command just retrieves the single `index.html` redirect page. If you update the command to:

```
!wget -r -A.html -P rtdocs https://python.langchain.com/en/latest/
```

It will work as intended!

**Comment by jamescalam** [comment] 2023-04-13 14:55
@ted-at-openai @neilobremski it should be fine to close this issue now

**Closed** 2023-04-14 22:57 UTC
